name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  IS_MASTER_BRANCH: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  PIPENV_CACHE_DIR: $(Pipeline.Workspace)/.pipenv_cache

stages:
  - stage: test
    displayName: Test
    jobs:
      - job: test
        displayName: Test
        steps:
          - template: azure-pipelines-setup.yml

          - script: pipenv run check-types
            displayName: Validate Types

          - script: pipenv run lint
            displayName: Lint

          - script: pipenv run test
            displayName: Test

  - stage: publish
    displayName: Publish
    condition: eq(variables.IS_MASTER_BRANCH, true)
    dependsOn: test
    jobs:
      - job: publish
        displayName: Publish
        steps:
          - checkout: self
            persistCredentials: true
            clean: true

          - template: azure-pipelines-setup.yml

          - script: |
              git config --global user.email "semantic@release.com"
              git config --global user.name "Semantic Release"
              pipenv run publish
            displayName: Publish to PyPI

      - job: deploy
        displayName: Deploy
        steps:
          - template: azure-pipelines-setup.yml

          - script: |
              npm install -g serverless
              serverless plugin install -n serverless-python-requirements
            displayName: Install Serverless

          - script: pipenv run sls deploy
            displayName: Deploy Serverless

  - stage: smoke_test
    displayName: SmokeTest
    condition: eq(variables.IS_MASTER_BRANCH, true)
    dependsOn: publish
    jobs:
      - job: smoke_test
        displayName: SmokeTest
        steps:
          - task: LambdaInvokeFunction@1
            inputs:
              awsCredentials: lambda-deploy
              regionName: ap-southeast-2
              functionName: ConversationAssistant
              payload: |
                {
                  "body": "{\"previous_messages\":[{\"text\":\"Dad, Jordyn and I might be having lunch around Camberwell tomorrow afternoon. I'm not sure where or what time yet but I could probably pick you up on the way home\",\"author\":\"Ben Kerr\"},{\"text\":\"I'm probably not going to be ready until 7ish tomorrow cause Eltham, but I'll keep you updated\",\"author\":\"Me\"},{\"text\":\"Keen for another look at that prescious mug\",\"author\":\"Ben Kerr\"},{\"text\":\"A coffee mug?\",\"author\":\"Ben Kerr\"},{\"text\":\"Your mug baby\",\"author\":\"Me\"},{\"text\":\"Oh right lol. I'm meeting for lunch at. I'll probably be home by 5\",\"author\":\"Ben Kerr\"}],\"gpt3_params\":{\"randomness\":0.7,\"num_results\":3,\"max_length\":50}}"
                }
