steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9.x"
    displayName: Install Python

  - bash: pip3 install pipenv
    displayName: Get Pipenv

  - bash: pipenv run install
    displayName: Install Dependencies
