steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9.x"
    displayName: "Install Python"

  - bash: pip3 install pipenv
    displayName: Get Pipenv

  - bash: |
      cat > .env << EOF
      PYPI_USERNAME=$(PYPI_USERNAME)
      PYPI_PASSWORD=$(PYPI_PASSWORD)
      GH_TOKEN=$(GH_TOKEN)

      OPENAI_API_KEY=$(OPENAI_API_KEY)

      PIPENV_VENV_IN_PROJECT=true
      PIPENV_IGNORE_VIRTUALENVS=1

      EOF
    displayName: Setup Environment

  - bash: pipenv run install
    displayName: Install Dependencies
