name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  IS_MASTER_BRANCH: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  PIPENV_CACHE_DIR: $(Pipeline.Workspace)/.pipenv_cache

stages:
  - stage: test
    displayName: Test
    jobs:
      - job: test
        displayName: Test
        steps:
          - template: azure-pipelines-setup.yml

          - script: pipenv run check-types
            displayName: Validate Types

          - script: pipenv run lint
            displayName: Lint

          - script: pipenv run test
            displayName: Test

  - stage: publish
    displayName: Publish
    condition: eq(variables.IS_MASTER_BRANCH, true)
    dependsOn: test
    jobs:
      - job: publish
        displayName: Publish
        steps:
          - checkout: self
            persistCredentials: true
            clean: true

          - template: azure-pipelines-setup.yml

          - script: |
              git config --global user.email "semantic@release.com"
              git config --global user.name "Semantic Release"
              pipenv run publish
            displayName: Publish to PyPI

      - job: deploy
        displayName: Deploy
        steps:
          - template: azure-pipelines-setup.yml

          - script: yarn
            displayName: Install Serverless

          - script: pipenv run yarn sls deploy
            displayName: Deploy Serverless
