variables:
  IS_MASTER_BRANCH: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

jobs:
  - job: Test
    steps:
      - template: azure-pipelines-setup.yml

      - bash: pipenv run check-types
        displayName: Validate Types

      - bash: pipenv run lint
        displayName: Lint

      - bash: pipenv run test
        displayName: Unit Test

      - bash: pipenv run teste2e
        displayName: E2E Test

  - job: Deploy
    condition: eq(variables.IS_MASTER_BRANCH, true)
    dependsOn: Test
    steps:
      - template: azure-pipelines-setup.yml

      - bash: |
          gcloud functions deploy generate_suggestions \
            --runtime python39 \
            --trigger-http \
            --allow-unauthenticated
        displayName: Deploy Cloud Function
