[tool.semantic_release]
version_variable = [
    'setup.py:__version__',
]
repository_url = "https://pypi.org/project/conversation_assistant/"

[tool.black]
line-length = 140

[tool.isort]
profile = "black"
