service: conversation-assistant
frameworkVersion: "2"
useDotenv: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true

provider:
  name: aws
  runtime: python3.9
  stage: local
  region: ap-southeast-2
  stackName: conversation-assistant-stack
  apiName: conversation-assistant-api
  lambdaHashingVersion: 20201221

package:
  patterns:
    - "!**"
    - "conversation_assistant/**"
    - "!conversation_assistant/test/**"
    - ".env"
    - "handler.py"

functions:
  generate-message-suggestions:
    name: ConversationAssistant
    handler: handler.lambda_handler
    description: Returns a list of message suggestions based upon previous messages
    events:
      - http: POST /generate
