service: conversation-assistant

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.9
  stage: local
  region: ap-southeast-2
  stackName: conversation-assistant-stack
  apiName: conversation-assistant-api
  lambdaHashingVersion: 20201221

package:
  patterns:
    - "!**"
    - ".venv/Lib/site-packages/**"
    - "conversation_assistant/**"
    - "!conversation_assistant/test/**"
    - "!**/__pycache__/**"
    - "handler.py"

functions:
  generate-message-suggestions:
    name: ${sls:stage}-conversation-assistant
    handler: handler.lambda_handler
    description: Returns a list of message suggestions based upon previous messages
