name: Daily Firestore Backup

# on:
#   schedule:
#     - cron: "0 0 * * *"
#   workflow_dispatch:
on:
  push:
    branches: [fix/omit-missing-params-from-prompt]
  workflow_dispatch:

env:
  GCP_PROJECT_NAME: conversation-assistant-dev
  GCP_BUCKET: gs://conversation-assistant-dev-bucket-firestore-backup

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: GCP Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEV_GCP_CREDENTIALS }}

      - name: GCP Setup
        uses: google-github-actions/setup-gcloud@v0.6.0

      - run: gcloud info

      - run: gcloud config set project $GCP_PROJECT_NAME

      - run: gcloud info

      - run: gcloud firestore export $GCP_BUCKET
