name: Daily Firestore Backup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GCP_PROJECT_NAME: conversation-assistant-dev
  GCP_BUCKET: gs://YOUR-BUCKET

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: GCP Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEV_GCP_CREDENTIALS }}

      - run: gcloud config set project ${{ env.GCP_PROJECT_NAME }}

      - run: gcloud firestore export ${{ env.GCP_BUCKET }}
