name: Firestore Backup Prod

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

env:
  GCP_PROJECT_NAME: conversation-assistant-prod
  GCP_BUCKET: gs://conversation-assistant-prod-bucket-firestore-backup

jobs:
  backup:
    runs-on: ubuntu-22.04
    steps:
      - name: GCP Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.PROD_GCP_CREDENTIALS }}

      - name: GCP Setup
        uses: google-github-actions/setup-gcloud@v0

      - name: Export Firestore data
        run: gcloud firestore export $GCP_BUCKET
